### PR TITLE
Object Detection NanoDet

### PR DESCRIPTION
**Pull request by Sidd1609**
Commits for Object_Detection_NanoDet
Nanodet Files:
- License
- ReadME
- Nanodet ONNX model (FP32 and Quantised FP16 model)
- Demo.py
- NanoDet.py
- Examples

### CODE REVIEW

**Comment by fengyuentau** [comment]
@Sidd1609 Can you add me as collaborator in your fork of opencv_zoo? I am pushing some changes to your branch before merge.

**Comment by fengyuentau** [comment]
I pushed some changes before merge. Code and models are verified on my side. Please take a look if changes are fine. If no problems, I will merge as-is soon.

**Comment by Sidd1609** [comment]
> @Sidd1609 ~Can you add me as collaborator in your fork of opencv_zoo? I am pushing some changes to your branch before merge.~ Never mind, I figured it out.

I have added you as collaborator to the repo.

**Comment by Sidd1609** [comment]
> I pushed some changes before merge. Code and models are verified on my side. Please take a look if changes are fine. If no problems, I will merge as-is soon.

Yes, I have reviewed the changes.

**Comment by fengyuentau** [comment]
Original test images in example/test_data are uploaded to gdrive in https://github.com/opencv/opencv_zoo/pull/106. So they will be removed from the pull request to save space.

**Review by fengyuentau — APPROVED** [review]
👍 Thanks for your hard work! Benchmarking data of this model will be provided in https://github.com/opencv/opencv_zoo/pull/106.

**Comment by Sidd1609** [comment]
Happy to contribute ✌️

**Pull request merged**
