### PR TITLE
benchmark: add vittrack benchmark results

### PR DESCRIPTION
**Pull request by fengyuentau**
Relates https://github.com/opencv/opencv/issues/24460
Relates https://github.com/opencv/opencv/issues/24154

VitTrack on CANN will be supported in the next patch. Merge this PR for now.

### CODE REVIEW

**Comment by fengyuentau** [comment]
VitTrack on CANN will be supported in the next patch. Merge this PR for now.

**Comment by fengyuentau** [comment]
@WanliZhong Please take a look.

**Comment by fengyuentau** [comment]
@WanliZhong Friendly reminder.

**Review by WanliZhong — APPROVED** [review]
👍LGTM

**Pull request merged**
