### PR TITLE
Add more demos to front page

### PR DESCRIPTION
**Pull request by fengyuentau**

### CODE REVIEW

**Comment by fengyuentau** [comment]
@zihaomu Can you provide some demos of DB and CRNN?

**Review by zihaomu — APPROVED** [review]
LGTM! 👍

**Comment by Charles-258** [comment]
您好，我是王仡垚，您的邮件我已经收到，我会尽快回复。

**Comment by the-star-sea** [comment]
I will do it this week.

**Review by ShiqiYu — APPROVED** [review]
Good to put more examples on the front page.

**Pull request merged**
