### PR TITLE
Add DB float16

### PR DESCRIPTION
**Pull request by the-star-sea**
add two DB quantized models

### CODE REVIEW

**Comment by fengyuentau** [comment]
@the-star-sea @zihaomu What is the status of this pull request? Do you plan to continue it?

**Comment by the-star-sea** [comment]
This has been done. Actually it depends on the need of your group.

**Comment by the-star-sea** [comment]
Previously, zihao told me that we didn't need the function so that I transferred it as a draft.

**Comment by the-star-sea** [comment]
Maybe we can simply have a chat to communicate the need and function design and I am available these days @zihaomu @fengyuentau.

**Comment by zihaomu** [comment]
Hi @the-star-sea, can your change this PR to ready? 
I propose to merge this PR first. For now, pp-OCR has not been supported, this PR wants to add float16 models. It's a supplement for us.

**Comment by fengyuentau** [comment]
If we are merging this PR, we need to remove the old fp32 models and replace with the fp16 models in this PR. Also need to add a note in README specifying the required minimum version of opencv that supports fp16 models.

**Comment by fengyuentau** [comment]
Closing for no activities.

**Pull request closed without merging**
