### PR TITLE
ObjectDetection YoloX

### PR DESCRIPTION
**Pull request by Sidd1609**
Commits for Object_Detection_YoloX 
YoloX Files: 
- License 
- ReadME 
- YoloX ONNX model (FP32 and Quantised FP16 model)(yolox_tiny, yolox_s,yolox_nano)
- Demo.py 
- YoloX.py 
- Examples

### CODE REVIEW

**Comment by fengyuentau** [comment]
I pushed some changes before merge. Code and models are verified on my side. Please take a look if changes are fine. If no problems, I will merge as-is soon.

**Comment by Sidd1609** [comment]
> I pushed some changes before merge. Code and models are verified on my side. Please take a look if changes are fine. If no problems, I will merge as-is soon.

Yes, I have reviewed the changes. Looks good we can merge it to the main.

**Comment by fengyuentau** [comment]
Original test images in example/test_data are uploaded to gdrive in https://github.com/opencv/opencv_zoo/pull/106. So they will be removed from the pull request to save space.

**Comment by Sidd1609** [comment]
Understood, so there is no need for examples to be used on the branch ?
Including the video inference sample

**Comment by fengyuentau** [comment]
> Understood, so there is no need for examples to be used on the branch ?
Including the video inference sample

No. We need samples including the gif, but original test images will be moved to gdrive to reduce the size of this repository.

**Comment by Sidd1609** [comment]
Understood.

**Review by fengyuentau — APPROVED** [review]
Thank your for the hard work👍 Benchmarking data will be provided in #106 .

**Pull request merged**
