### PR TITLE
add benchmark for optical flow Raft model

### PR DESCRIPTION
**Pull request by WanliZhong**

### CODE REVIEW

**Comment by WanliZhong** [comment]
Fail on CANN backend. 
```
[ WARN:0@5.268] global net_cann.cpp:120 initBackend DNN/CANN: layer (name=onnx_node!InstanceNormalization_16/MVN, type=MVN) is not supported by CANN backend. Going back to default backend on CPU target
```

**Comment by fengyuentau** [comment]
> Fail on CANN backend.
> 
> ```
> [ WARN:0@5.268] global net_cann.cpp:120 initBackend DNN/CANN: layer (name=onnx_node!InstanceNormalization_16/MVN, type=MVN) is not supported by CANN backend. Going back to default backend on CPU target
> ```

It should not go to MVN. We have dedicated instance norm layer already.

**Comment by WanliZhong** [comment]
Benchmark is already done. Raft run very very slow. I set 30s as the accepted time for the color table.

**Comment by fengyuentau** [comment]
Thanks for the hard work. I propose not to put this model into the benchmark table. Lets discuss in the meeting.

**Pull request closed without merging**
